doc/cheatsheet/cheatsheet.tex
doc/tutorial/tutorial.tex

minor typo in the cheatsheet + CRLF -> LF cleanup in cheatsheet

---

src/main/scala/Verilog.scala
src/test/resources/NameSuite_BindFifthComp_1.v
src/test/resources/NameSuite_BindFirstComp_1.v
src/test/resources/NameSuite_VecSecondComp_1.v

Could the Verilog gurus exercise this please?

Randomize unconnected Verilog wire values (as we do for the C++ backend) #191.

---

README.md
doc/Makefile

Work around htlatex and pdflatex .aux file interaction.
Run *latex tools twice to ensure references are handled correctly.

Update document generation and instructions.

---

src/main/scala/Driver.scala
src/main/scala/Null.scala
src/main/scala/Tester.scala

Added null backend (--backend null).
Added --testCommand

Support for test only.

---

src/test/scala/TestSuite.scala

If we're running the tester with the C++ backend and "partitionIslands" is defined in the environment, use its definition as arguments for a second round of Cpp tests. We should use ScalaTest specifications for this - multiple tests under different inputs or test conditions.

Enable additional tests (partitionIslands) via environment variables.

---

src/main/scala/Cpp.scala

We need at least two cpp files in order to compile with different optimization levels (until we can rely on per-function optimization).

Ensure we generate multiple cpp files (when instructed to do so).

---

src/main/scala/ChiselError.scala
src/main/scala/SysC.scala
src/main/scala/hcl.scala
src/test/scala/SystemCSuite.scala

Use ChiselError() instead of "throw RuntimeException()".
Once we've found the user class containing the problem line, look for anonymous methods/classes in that class in lower stack frames.

Use the standard Chisel error mechanism in SystemC backend - #431

---

src/main/resources/emulator_api.h
src/main/resources/emulator_mod.h

Minor fixup to Steven's pr #434

Heedcompilerwarnings

---

src/main/scala/Module.scala

toString of IOs is very noisy. Instead, only prints name, type, and its module.
also fixes addPin in Module.scala

more informative error messages for IOs

---

src/main/scala/ChiselUtil.scala
src/main/scala/Fixed.scala
src/test/scala/FixedTest.scala

Implemented a basic(and rather hardware intensive) modulo operator for Fixed
Updated FixedTest with modulo test
Updated ShiftRegister, replaced default arguments with a series of apply methods
Updated Fixed with getFractionalWidth, included Unit tests for Fixed
Added a ShiftRegister apply with an init
Added Fixed from Chisel Linear Algebra

Fixed Point data type that extends Bits with Num[Fixed] #444

---

src/main/scala/Backend.scala
src/main/scala/Node.scala
src/main/scala/Op.scala
src/main/scala/SInt.scala
src/main/scala/UInt.scala
src/test/resources/ZeroWidthTest_MulZS_1.dot
src/test/resources/ZeroWidthTest_ZeroWidthForceMatching_1.v
src/test/scala/ZeroWidthTest.scala

Fix for "Chisel somehow finds a way to build negative width wires" - #439 (plus tests and attempt to deal with s*u width assumptions).

Zerowidthforcematching439

---

Makefile
src/main/resources/template.txt
src/main/scala/SCWrapper.scala
src/main/scala/SysC.scala
src/test/scala/SysCTest/AddFilter.scala
src/test/scala/SysCTest/FullAdder.scala

Add support for top-level Bundles.
Move SystemC tests into their own test directory.

Systemc top-level aggregate signal support

---

src/test/scala/BitsTest.scala
src/test/scala/DataTest.scala
src/test/scala/FixedTest.scala

Test cases are no longer executed after commit b86b4cd8

Fix to test cases

---

src/main/scala/Mem.scala

Have SeqMem extend Delay with VecLike (and provide setName()).

SeqMem class inherits setName()

---

src/main/scala/Backend.scala
src/main/scala/Cpp.scala

Rather than just failing to compile, give an informative message

Added some error checking for redeclarations

---

README.md

Just starting to look at this project, sounds really a cool piece of code!
Hope this is appreciated.

Added deps for docs build on Mac.

---

src/main/resources/emulator.h

Fixes #510 
Strange stuff is still happening
I don't know why but the for loop isn't terminating with clang
Work on it more later, don't merge yet

Add fix for rsh emulator which had seg fault on uninitialized values

---

src/main/resources/emul_api.h
src/main/resources/emulator.h
src/main/resources/vpi.h
src/main/scala/Tester.scala
src/main/scala/Vcd.scala

Fix tester

---

src/main/scala/Vcd.scala

See
https://github.com/ucb-bar/chisel/commit/de14ec83308a72b04c77b56b614eba42b050ddc7#commitcomment-13086736
for details.

Fixed vcdMem regression introduced in v28.

---

src/main/scala/ChiselUtil.scala

Putting in a negative number into shift register resulted in a stack overflow. Have chisel error instead

Error checking for shift register

---

src/main/scala/ChiselUtil.scala

Here is some little documentation fixes for Queue in ChiselUtil.
I still doesn't understand correctly 'flow' and 'pipe' parameters.

Some documentation fix for Queue in ChiselUtil

---

src/main/scala/ChiselUtil.scala

Minor textual changes to #497.

 Comments and slight modifications to ChiselUtil  - #497

---

src/main/resources/vpi.h
src/main/scala/Tester.scala
src/main/scala/Verilog.scala
src/test/scala/NameTest.scala

This is small fixes for tester

Fix misc 2

---

src/main/scala/Backend.scala
src/main/scala/Cpp.scala
src/main/scala/Dot.scala
src/main/scala/FameBackend.scala
src/main/scala/Node.scala

This should produce more useful error messages with source file and line number.

Address issue #528 - generate ChiselError for asserts().

---

src/main/scala/Mem.scala

While refactoring hwacha code to follow Chisel3's Mem/SeqMem write method with masks, I noticed that it's not fully implemented in Chisel2.  This PR fixes that.

make Mem write method compatible with Chisel3

---

src/main/resources/emulator.h

Added comments to rsha_n for readability

---

src/main/scala/ChiselUtil.scala

Example of Queue object was that of Queue class.

fix Queue object example and add Pipe object example

---

src/main/scala/Reg.scala
src/test/scala/RegWithAgregateDefaultSuite.scala

Add test for Regs with aggregates. Addresses #603.

When validateGen() fails in Reg, mention the failing element - #603

---

src/main/resources/emul_api.h

Fix incorrect VCD - #609.

---

src/main/resources/emul_api.h
src/main/resources/emulator.h
src/main/scala/Cpp.scala
src/main/scala/Tester.scala
src/main/scala/Vcd.scala
src/test/resources/ConnectSuite_UnconnectedIOs_1.h
src/test/resources/DelaySuite_ROMModule_1.cpp
src/test/resources/DelaySuite_ROMModule_1.h
src/test/resources/DelaySuite_SeqReadBundle_1.cpp
src/test/resources/DelaySuite_SeqReadBundle_1.h
src/test/resources/NameSuite_DebugComp_1.cpp
src/test/resources/NameSuite_DebugComp_1.h
src/test/resources/VerifSuite_CppAssertComp_1.cpp
src/test/resources/VerifSuite_CppPrintfComp_1.cpp
src/test/resources/VerifSuite_CppPrintfComp_1.h

Fix vcd dump

---

src/test/resources/RegVcdSuite_RegVcdTest_1.vcd
src/test/scala/RegVcdTest.scala
src/test/scala/TestSuite.scala

Add a test case for the VCD output of register signals.
Integrate with the Scalatest JUnit infrastructure.

Schoeberl vcd test

---

src/test/resources/RegVcdTest.vcd
src/test/scala/RegVcdTest.scala

The test is currently only a stand alone main as I am not so familiar with the test environment. Someone else more fluent in the Chisel development could help to integrate that test.

Add a test case for the VCD output of register signals

---

src/test/scala/FunTestSuite.scala
src/test/scala/TestHelpers.scala
src/test/scala/TestSuite.scala

Refactor TestSuite (create TestHelpers).
Add FunTestSuite for ScalaTest FunSuites.

Add support for non-JUint tests.

---

doc/tutorial/tutorial.tex

Minor fixes. We should address the %MS points raised by Martin.

Schoeberl tutorial

---

src/main/scala/Tester.scala

Add a method to pass in Booleans to expect method in tester
Is just a wrapper for expect(Bits, Int)

Add expect(Bool, Boolean) methods

---

src/main/scala/Tester.scala

An alternative to #671 (which fails the FlushPrintfOutput tests.)

Another printf output fix

---

src/main/scala/BlackBox.scala
src/main/scala/hcl.scala

Moved BlackBox to its own file

Migrated black box to separate file

---

src/main/scala/Vec.scala
src/test/scala/VecApp.scala

Vec.fill appears to be badly broken

Remove extraneous apply() from vec.tabulate - #718

---

build.sbt
src/main/scala/iotesters/ChiselSpec.scala
src/main/scala/iotesters/Driver.scala
src/main/scala/iotesters/HWIOTester.scala
src/test/scala/TesterTest.scala

Add scalacheck as a library dependency.
Move ChiselSpec.scala from test to main.

Add support for new chisel3 tutorials.

---

src/main/scala/Bits.scala
src/main/scala/Bundle.scala
src/main/scala/Node.scala

Make their definitions available to Aggregates.
Add them to Bundle keywords.

Move chisel3 compatible casts {as,to}{S,U}Int from Bits to Node.
