doc/style/scala.tex, doc/tutorial/tutorial.tex
Fixed a typo (left-hand side / right-hand side) and a LaTeX mistake (% is not a comment character within lstlisting environments unless you escape back to LaTeX mode).
=> Tutorial fixes

src/main/scala/Verilog.scala, src/test/resources/ConnectSuite_UnconnectedResets_1.v, src/test/resources/DelaySuite_MemReadModule_1.v, src/test/resources/DelaySuite_ROMModule_1.v, src/test/resources/DelaySuite_ReadCondMaskedWrite_1.v, src/test/resources/DelaySuite_ReadCondWriteModule_1.v, src/test/resources/DelaySuite_ReadWriteModule_1.v, src/test/resources/DelaySuite_RegInitCondUpdate_1.v, src/test/resources/DelaySuite_RegInitUpdate_1.v, src/test/resources/DelaySuite_RegNoInitUpdate_1.v, src/test/resources/MultiClockSuite_Comp_1.v, src/test/resources/MultiClockSuite_TestMultiClock2_1.v, src/test/resources/NameSuite_BindFifthComp_1.v, src/test/resources/NameSuite_BindFirstComp_1.v, src/test/resources/NameSuite_MemComp_1.v, src/test/resources/NameSuite_VecComp_1.v, src/test/resources/NameSuite_VecSecondComp_1.v, src/test/resources/StdlibSuite_PipeComp_1.v, src/test/resources/StdlibSuite_QueueComp_1.v, src/test/resources/StdlibSuite_RRArbiterTest_1.v, src/test/resources/VerifSuite_VerilogAssertComp_1.v, src/test/resources/VerifSuite_VerilogPrintfComp_1.v, src/test/resources/VerifSuite_VerilogPrintfNULComp_1.v
Several tools define SYNTHESIS for the Verilog preprocessor when performing
synthesis, as opposed to simulation.  Quartus doesn't, but it is part of a
handful of tools that respect //comment directives that have the same
effect.  So emit both.
=> Support Quartus' variant of `ifndef SYNTHESIS

Makefile
The instrumented version of the code (sbt test) contains references to the instrumentation modules, requiring clients to include those packages with their code.
=> Don't publish the instrumented version of the code.

src/main/resources/emulator_api.h, src/main/resources/emulator_mod.h
EMail of 3/12/2015, 7:30pm, Re: Chisel with Scala 2.11.4
Some nit's on the emulator*.h code:
Seen in a few places:
emulator_mod.h:1722:3: error: 'mod_t' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
Worked around with: -Wno-non-virtual-dtor
Should be std::string below for consistency
emulator_api.h:240:2: error: reference to 'string' is ambiguous
string get_element(std::string index)
emulator_api.h:355:27: error: reference to 'string' is ambiguous
std::string eval_command(string command)
Fixed locally.
Uninitialized value:
emulator_api.h:467:15: error: variable 'success' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
} else if (tokens.size() == 4) {
^~~~~~~~~~~~~~~~~~ …
=> Observations/suggestions from Doug Hogberg at Google.

src/main/scala/SInt.scala, src/test/scala/StdlibTest.scala
Use getWidthW() instead of widthW in SInt.matchWidth() to get the
current node's width, so if we can infer it we will.
=> Fix Data width lost in Vec #384.

src/main/scala/Module.scala, src/test/scala/ModuleTests.scala
If we end up wrapping a bare Module() with Module (no intervening
component), issue an error message instead of:
Exception in thread "main" java.util.NoSuchElementException: head of empty list
at scala.collection.immutable.Nil$.head(List.scala:420)
at scala.collection.immutable.Nil$.head(List.scala:417)
at scala.collection.mutable.Stack.pop(Stack.scala:140)
at Chisel.Module$.pop(Module.scala:87)
at Chisel.Module$.Chisel$Module$$init(Module.scala:59)
=> Detect and issue an error for double Module() wrapping - #385

src/main/scala/Backend.scala, src/main/scala/ChiselError.scala, src/main/scala/Module.scala, src/main/scala/Node.scala, src/test/scala/ConnectTest.scala, src/test/scala/DataTest.scala, src/test/scala/ModuleTests.scala, src/test/scala/StdlibTest.scala, src/test/scala/VerifTest.scala, src/test/scala/ZeroWidthTest.scala
Several clients were adding errors to ChiselError.ChiselErrors directly which unfortunately doesn't update ChiselError.hasError which is used by ChiselError.checkpoint() to determine if it should abort or not. We could have changed hasErrors to basically do a ChiselErrors.isEmpty, but the ArrauBuffer contains warnings as well so currently, hasErrors != isEmpty.
=> make ChiselErrors private so clients are forced to use Chisel.error() - #393

src/main/scala/hcl.scala, src/test/scala/TestSuite.scala
Circumvent problems with getting test arguments through the test runners by making them available through the environment.
Update TestSuite to check for partitionIslands arguments using the same mechanism.
=> Provide chiselEnvironmentArguments() to fetch arguments from the environment.

src/main/scala/ChiselUtil.scala, src/main/scala/Vec.scala, src/main/scala/hcl.scala, src/test/scala/BundleWire.scala, src/test/scala/ComplexAssign.scala, src/test/scala/ConnectTestWire.scala, src/test/scala/Outer.scala, src/test/scala/Risc.scala, src/test/scala/TestSuite.scala, src/test/scala/VecApp.scala
In order to ease migration to Chisel3, add support for Wire().
Incorporate some tests from chisel3-tests to verify functionality.
=> Added Wire() no-op (support for Chisel3) and associated tests.

src/main/scala/Backend.scala, src/main/scala/Cpp.scala, src/main/scala/Driver.scala, src/main/scala/Node.scala, src/main/scala/Op.scala, src/main/scala/PartitionIslands.scala
Reduce resources consumed during graph construction and C++ generation.
Fix logic for generating multiple C++ files; set minimumLinesPerFile to a reasonable default.
Move clkDomains.populate() back before any output is generated.
Performance optimization - use the list of islands per node (--partitionIslands).
=> Megaboomresources - reduce memory required by large designs

src/main/scala/Cpp.scala, src/main/scala/Driver.scala
Reduce the default minimumLinesPerFile to 10000.
Add an opportunity to create a cpp file between clock_lo() and clock_hi().
=> Reduce size, increase number of cpp files (Cpp Backend).

src/main/scala/Driver.scala
isInlineMem wasn't initialized in initChisel() causing testSeqReadBundle() in DelaySuite to fail if it followed a test that set isInlineMem false.
=> Ensure all driver variables are initialized in initChisel() - #424

src/main/resources/emulator_api.h, src/main/resources/emulator_mod.h
These pragmas intentionally suppress a wide swath of compiler warnings,
which hinders debugging of issues in the file. Their presence (and broad
scope) is also a negative indicator of code quality. Removal should also
make tracking down issues related to #410 much easier as the compiler
will then properly emit warnings.
=> Stop suppressing compiler warnings for emulator library

src/main/resources/emulator_mod.h, src/main/scala/Cpp.scala, src/main/scala/Driver.scala
This adds a new Chisel option "--assertWarn" which changes the emitted
C++ backend to evoke more warning-like behavior. With this flag enabled,
the C++ backend uses a new "WARN" macro (which prints the assertion
message) instead of the "ASSERT" macro (which triggers an exception).
The Verilog backend is unchanged as assertions are currently printed to
stderr and won't kill a simulation.
As there are three options now, "--noAssert" takes precedence with
"--assertWarn" overriding the default-enabled "--assert". The Verilog
backend ignores "--assertWarn".
This should address #437.
=> Add --assertWarn flag converting Assert to Warn

src/test/scala/Risc.scala
Add TestSuite wrapper.
Add use of peekAt().
Use explicit pokes() instead of implicit (eliminate tick(), so we don't run clock_lo multiple times when starting (k==0).
=> Add Risc to tests.

src/main/scala/Extract.scala, src/main/scala/Insert.scala, src/test/scala/Chisel3Compatibility.scala
The folowing should pass without a Wire wrapper.
val foo = Reg(Bits(width = 16))
foo(0) := UInt(1)
=>  Insert and Extract are not TypeOnly nodes.

src/main/resources/Makefile, src/main/scala/Cpp.scala
Eliminate the dependency on a "clone" method (and associated file) for multiple cpp file generation.
Fix count and prototype/call discrepancies when generating multiple sim_data_init methods.
Only add signals that actually made it into the simulation to the signal map. Otherwise, we end up generating initializations using bad signal names (for those nodes that didn't get renamed), and the c++ compilation fails.
=> Fix Cpp Backend issues with new no_strings_tester.

src/main/scala/Mem.scala
macro names fixed for the VLSI flow.  This pull request adds setName
to the new Seq class.
=> The Mem class used to inherit setName which was useful for keeping

src/main/scala/Fixed.scala, src/test/scala/FixedTest.scala
Updated this.fractionWidth to use the getter (this.getFractionalWidth())
Changed the default multiplication to keep of the multiplication bits
Moved multiplication by truncation to *%
Updated fromSInt to ensure that the resulting width is consist for operation
Updated *% and *& to ensure that the resulting width and fractional width are the same as the multiplier inputs
Updated % to just do the normal integer modulo by transforming the inputs into integers
Made a small change the colonEqual to handle the case where you assign a Fixed number to another which is half of the width and fractional length.
Added two truncate helper functions
Updated check aligned to ensure that both the widths and fractional widths are the same
Added test cases for the changes above
=> Fixed Update

src/main/scala/Enum.scala
Scala has a built in size limitation on the size of a Tuple of 22 (https://groups.google.com/forum/#!topic/scala-language/wE1eLIOBBR4). This becomes a problem if you try to define an Enum in the "standard" way as outlined in the documentation. 
This updates the documentation to make this issue known and provides a new example for how to use one of the alternative methods which does not have this size 22 limitation.
=> Update Enum Doc for Scala's limit on Tuple size

src/main/scala/ChiselUtil.scala
There is a bug in AsyncFifo, entries number is «arrounded» with asize : 
val asize = log2Up(entries)
And used as this through all fifo pointers. But Memory Mem() is not arrounded according to asize.
Here is a proposal-patch to solve this problem : entries is automatically arrounded by 2^n.
=> The actual size of fifo and Mem() must be arrounded in the upper 2^n

build.sbt, project/plugins.sbt, src/main/scala/Driver.scala
We encounter
error: not found: value sbtbuildinfo
enablePlugins(sbtbuildinfo.BuildInfoPlugin).
when this plugin is enabled in a submodule (project) and the root project uses project/build.scala
=> Revert BuildInfo code due to problems when included as a submodule.

src/main/scala/Mem.scala
The addition of setName does not actually allow naming of memories in a
consistent way. This patch adds a setMemName method that accomplishes
what was originally intended for the overridden setName.
=> Replace overridden setName in seqMem with a working setMemName method

src/main/scala/ChiselUtil.scala, src/main/scala/FameBackend.scala, src/main/scala/Mem.scala, src/main/scala/Vec.scala, src/test/scala/BundleWire.scala, src/test/scala/DelayTest.scala, src/test/scala/Risc.scala, src/test/scala/SeqMemSuite.scala, src/test/scala/VecApp.scala
(Deprecated Vec(out,n),Mem(out,n) and added Vec(n,t),Mem(n,t)).
- This change, in preparation for Chisel3, makes Vec declarations
more readable by putting the number of elements first.
- It also makes Mem() consistent with the new Vec() syntax.
- It changes ChiselUtil to use the new Mem().
=> Swapped arguments (out,n) in Vec and Mem.

src/main/scala/Verilog.scala
OpenSoC creates at least one module with no uncommented ports, triggering a java.lang.UnsupportedOperationException: empty.init when we try to add a trailing comma to each declaration.
=> Avoid java.lang.UnsupportedOperationException: empty.init when no uncommented ports - fix for #545

src/main/scala/Backend.scala, src/test/scala/NameTest.scala
Slight change to pr499 - ignore attempts to reserve empty names.
Fixes #459.
=> Incorporate pr499 - don't reserve empty names.

src/main/scala/Tester.scala, src/test/scala/FlushPrintfOutput.scala
Rename testOutputString to accumulatedTestOutput and provide a mechanism to fetch the last output line.
Convert _logs to ArrayBuffer (from Queue) and use a last-printed index to track what's been printed so far.
This allows is to keep a single copy of all the printf output, accessible on an individual line basis (if so-desired).
=> Fix printf output collection to pass FlushPrintfOutput test.

src/main/scala/Tester.scala, src/test/scala/AssertSuite.scala
Detect abort messages from the test application - avoid "java.io.IOException: Stream closed” - #559
=> Handle run-time test application assertions (abort()) - issue #559

src/test/scala/NameTest.scala
Since the order of test runs is indeterminate, we can't assume testKeywordsCpp() or testKeywordsVerilog() have run before testKeywordsNull(). The latter needs to prepare its test environment independently of other tests.
=> Ensure testKeywordsNull() has an application to execute.

src/main/scala/ChiselUtil.scala, src/main/scala/Mux.scala, src/test/scala/StdlibTest.scala
This reverts some of the changes made in a4f5946c80e9e3533322477eccc7396db0c9d1a3. See commit message in https://github.com/ucb-bar/chisel/commit/31245360305f8ec1aa6b85cbfb7e0c5b5dceb614 for more details.
The type change should also allow Vec's to be used with these stdlib functions, but I have not tested this.
=> Re-introduce MuxCase / PriorityMuxi'ing of bundles

src/main/scala/ChiselUtil.scala, src/test/scala/ArbiterTest.scala
Add a new arbiter type named StableArbiter.
Stable arbiters ensure that the output of an arbiter is stable once out.valid is asserted.
This arbiter is necessary when the client device on the output side is slow and needs to latch the request content (out.bits) or to process the requests for extra cycles before asserting ready (out.ready).
The differences before the origin arbiter and a stable arbiter:
In stable arbiters, once there is one or more inputs becoming valid, the output is locked to the chosen input until it is fired for count times. Inputs with higher priorities cannot pre-empt a chosen input with lower priority if it comes late. (Priority is used only when multiple requests become valid at the same cycle).
Another choice could be adding another parameter after "needsLock", eg: …
=> add stable arbiters

src/main/resources/emulator.h, src/test/scala/LargeNumber.scala
I'm actually not sure this is correct, but the other version is
obviously wrong: it regularly shifts by an extremely large value (as the
result of unsigned underflow).  This actually manifests in rocket-chip,
Howie found and isolated a test case.
I found this using "-fsanitize=undefined" (kind of by accident, since as
far as I can tell this was just wrong), which seems like something that
should be run on emulator.h.  It's unfortunately a dynamic analysis, but
we should probably run it on rocket-chip.
=> Implement rsha_n correctly

src/main/resources/sim_api.h, src/main/scala/Tester.scala
Return -1 on getid() failure (instead of abrupt exit).
If we are going to exit prematurely, don't do a normal exit.
=> Avoid Tester hang on bogus peek()/poke() - #581.

src/main/scala/Tester.scala
Avoid "java.util.NoSuchElementException: next on empty iterator" and add exit code to exception string.
=> Check for empty _log on tester application exit - address #583

src/main/scala/ChiselUtil.scala
I had this error in my design : 
```scala
...
[error] avlmaster.scala:279: Cannot auto-create constructor for Chisel.QueueIO that requires arguments: List(class Chisel.Data, int) in class AvlMaster.AvlMasterWriteBurst
[error] avlmaster.scala:279: Parameterized Bundle class Chisel.QueueIO needs cloneType method in class AvlMaster.AvlMasterWriteBurst
...
```
If I add an overriding cloneType function in QueueIO, this error disappear.
=> adding cloneType override for QueueIO Bundle

src/main/resources/emulator.h, src/test/scala/FlushPrintfOutput.scala
Minor typo causing the string not to terminate and hence not print properly
=> Fixes 573, the number of digits in a float was miscalulated in a typo

src/main/resources/emulator.h, src/test/scala/FlushPrintfOutput.scala
Terminate formatted strings and verify we haven't overflowed allocated storage.
Add Flo printf output test.
=> printf output buffer is too small - #573

src/main/resources/sim_api.h
Follow comment and recommendation for #600, #601.
=> Use getpid() instead of rand() to ensure unique channel names.

src/main/scala/Dot.scala
Use diamond shape and label Mux inputs in dot backend output.
=> Provide more detail for mux inputs in dot backend output.

src/test/scala/SubwordTests.scala
This subword regression bug was introduced in 2.31 and will silently generate the wrong HW.
=> Added test case that provokes subword regression.

src/main/scala/Insert.scala
shiftedMask should be zero-extended, but ~shiftedMask should be sign-extended
=> fix broken subword

src/main/scala/Driver.scala
If we failed with a C++ compilation error, don't bother re-running with --lineNumbers since that won't add anything useful to the failure diagnostics.
=> Be more selective when re-running to enable line numbers.

src/main/resources/sim_api.h, src/main/scala/Tester.scala
Try to avoid IndexOutOfBoundsException at the start of simulation by ensuring the initial write at file creation time has been recorded, and verify that the channel file size is non-zero when we create the buffer for the memory-mapped channel.
=> fsync() the memory-mapped file and verify buffer size is non-zero #624

src/main/scala/Tester.scala
Peeking on a fixed currently doesn't do the right thing for negative numbers- this should fix that.
=> Add fixed to list of types that are signed for peek

src/test/resources/VCDVerifySuite_Top_1.vcd, src/test/scala/VCDComparator.scala
Since short names may be shuffled due to minor code changes, we should use long signal names. But these need to be qualified with the module name.
Report all disparate signals.
Use "hasNext" in place of "more" - reduce the cognitive load.
Fix initial signal set comparison.
=> Use long (original) signal names for comparison in VCDComparator().

build.sbt
generates class hierarchy diagrams in the html documentation
requires graphviz package to be installed to create diagrams
If it isn't installed will print a warning saying not found and generate original documentation
=> Include class hierarchy diagrams in scaladoc

src/main/scala/testers/TesterDriver.scala, src/test/scala/DecoupledGCD.scala, src/test/scala/GCDUnitTest.scala, src/test/scala/TestSuite.scala
Update copyright date; specify targetDir.
=> Simplify argument handling for the Chisel3 TesterDriver.

src/main/resources/sim_api.h, src/main/resources/vpi.cpp, src/main/scala/Cpp.scala, src/main/scala/Tester.scala, src/test/scala/TesterTest.scala
NOTE - This requires a new init_channels() method which must be called after init_sim_data().
Use symbolic constants in Tester.scala and sim_api.h for the channel data offset.
Run TesterTests with both C++ and Verilog backends (if the latter is available).
Add a test for dynamically sized channel code.
Update vcs support for big IOs.
=> Don't initialize the channels until we know how big they need to be - #655

src/main/scala/Verilog.scala
This fixes complaints in fpga synthesis due to extractions from single bit wires.
=> do not extract a single bit wire

src/main/scala/ChiselUtil.scala
The previous ones were incorrect for large inputs because of inexact
floating-point arithmetic.  These use BigInt so are exact.  This also
fixes log2Up(0) to conform to the documentation.
=> Improve log2* functions, as with Chisel3

src/main/scala/ChiselUtil.scala, src/main/scala/Data.scala, src/main/scala/Log2.scala, src/main/scala/Node.scala, src/main/scala/Parameters.scala, src/main/scala/ROM.scala, src/main/scala/Vec.scala
Iterable does not guarantee any particular ordering, whereas Seq does.
It should not be used when ordering actually matters.
This is technically an API-breaking change, but code that was relying on
it was kind of wrong, and would break in Chisel3 anyway.
=> Use Seq, not Iterable, when order matters

src/main/scala/ChiselUtil.scala
The return type actually used to be Seq, but it was inadvertently changed
to Vec at some point.
It doesn't really make sense to create a one-hot result then follow it
with a decoder.  It's more performant to use a PriorityEncoder followed
by a comparator.  Discourage the former by returning Seq, not Vec.
=> Return Seq, not Vec, from PriorityEncoderOH

src/main/scala/package.scala, src/test/scala/ArbiterTest.scala, src/test/scala/AssertSuite.scala, src/test/scala/BitPatSuite.scala, src/test/scala/BitsTest.scala, src/test/scala/Chisel3Compatibility.scala
This change allows chisel 2 to define literals using the new Chisel 3 notation
UInt(7) => 7.U
With this change we can change the tutorials to use the new idiom, and keep the tutorial runnable on either Chisel 2 or Chisel 3 without modification
=> add package object with new literal creation implicits

src/main/scala/Cpp.scala, src/test/scala/ROM.scala
If we're initializing wide ROMs, we may generate additional constants when we emit the initialization code. Ensure those constants make it into the constant pool (if we're using one).
=> Wide rom fix
